// <auto-generated />
using System;
using AtsManager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtsManager.Migrations
{
    [DbContext(typeof(AtsDbContext))]
    [Migration("20251018032144_InitialAtsSchema")]
    partial class InitialAtsSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AtsManager.Models.CargaLote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Anio", "Mes", "TipoArchivo")
                        .IsUnique();

                    b.ToTable("CargasLotes");
                });

            modelBuilder.Entity("AtsManager.Models.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("BaseImponibleIVA")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("BaseNoObjetoIVA")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("CargaLoteId")
                        .HasColumnType("int");

                    b.Property<string>("Establecimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HayRetencion")
                        .HasColumnType("bit");

                    b.Property<string>("IdentificacionProveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontoIVA")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("MontoIce")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("PuntoEmision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocialProveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Secuencial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoIdentificacionProveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CargaLoteId");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("AtsManager.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("BaseImponibleIVA")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("BaseNoObjetoIVA")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("CargaLoteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentificacionCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontoIVA")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RazonSocialCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoIdentificacionCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CargaLoteId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("AtsManager.Models.Compra", b =>
                {
                    b.HasOne("AtsManager.Models.CargaLote", "CargaLote")
                        .WithMany()
                        .HasForeignKey("CargaLoteId");

                    b.Navigation("CargaLote");
                });

            modelBuilder.Entity("AtsManager.Models.Venta", b =>
                {
                    b.HasOne("AtsManager.Models.CargaLote", "CargaLote")
                        .WithMany()
                        .HasForeignKey("CargaLoteId");

                    b.Navigation("CargaLote");
                });
#pragma warning restore 612, 618
        }
    }
}
