// <auto-generated />
using System;
using AtsManager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtsManager.Migrations
{
    [DbContext(typeof(AtsDbContext))]
    [Migration("20251018050643_FinalSchemaUpdate")]
    partial class FinalSchemaUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AtsManager.Models.CargaLote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TotalRegistros")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Anio", "Mes", "TipoArchivo")
                        .IsUnique();

                    b.ToTable("CargasLotes");
                });

            modelBuilder.Entity("AtsManager.Models.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("Anio")
                        .HasColumnType("smallint");

                    b.Property<decimal>("BaseImpGrav")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("BaseNoGraIva")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("CargaLoteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdProveedor")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<short>("Mes")
                        .HasColumnType("smallint");

                    b.Property<decimal>("MontoIce")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("MontoIva")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("NumComprobante")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("ParteRelacionada")
                        .HasColumnType("bit");

                    b.Property<string>("RazonSocialProveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("TipoIdProveedor")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorRetBienes")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ValorRetRenta")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ValorRetServicios")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CargaLoteId");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("AtsManager.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("Anio")
                        .HasColumnType("smallint");

                    b.Property<decimal>("BaseImpGrav")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("BaseNoGraIva")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("CargaLoteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdCliente")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<short>("Mes")
                        .HasColumnType("smallint");

                    b.Property<decimal>("MontoIce")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("MontoIva")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("NumComprobante")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("RazonSocialCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("TipoIdCliente")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CargaLoteId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("AtsManager.Models.Compra", b =>
                {
                    b.HasOne("AtsManager.Models.CargaLote", "CargaLote")
                        .WithMany()
                        .HasForeignKey("CargaLoteId");

                    b.Navigation("CargaLote");
                });

            modelBuilder.Entity("AtsManager.Models.Venta", b =>
                {
                    b.HasOne("AtsManager.Models.CargaLote", "CargaLote")
                        .WithMany()
                        .HasForeignKey("CargaLoteId");

                    b.Navigation("CargaLote");
                });
#pragma warning restore 612, 618
        }
    }
}
