// <auto-generated />
using System;
using AtsManager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtsManager.Migrations
{
    [DbContext(typeof(AtsDbContext))]
    [Migration("20260309232544_AddRetencionesComprasTable")]
    partial class AddRetencionesComprasTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AtsManager.Models.CargaLote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalRegistros")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CargasLotes");
                });

            modelBuilder.Entity("AtsManager.Models.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short?>("Anio")
                        .HasColumnType("smallint");

                    b.Property<string>("AplicConvDobTrib")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Autorizacion")
                        .IsRequired()
                        .HasMaxLength(49)
                        .HasColumnType("nvarchar(49)");

                    b.Property<decimal?>("BaseImpAir")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("BaseImpExe")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("BaseImpGrav")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("BaseImponible")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("BaseNoGraIva")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("CargaLoteId")
                        .HasColumnType("int");

                    b.Property<string>("CodRetAir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodSustento")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("CodigoCompra")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DenopagoRegFis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estab")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormaPago")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("IdProveedor")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<short?>("Mes")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("MontoIce")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("MontoIva")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("MontoTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("NumComprobante")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PagExtSujRetNorLeg")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("PagoLocExt")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("PaisEfecPago")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("PaisEfecPagoGen")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("PaisEfecPagoParFis")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("ParteRelacionada")
                        .HasColumnType("bit");

                    b.Property<decimal?>("PorcentajeAir")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("PtoEmi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocialProveedor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RucEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Secuencial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("TipoIdProveedor")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("TipoProveedor")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("TipoRegi")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ValRetAir")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("ValRetBien10")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("ValRetServ100")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("ValRetServ20")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("ValRetServ50")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("ValorRetBienes")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("ValorRetServicios")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("ValorRetencionNc")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CargaLoteId");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("AtsManager.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("CodEstablecimiento")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("AtsManager.Models.NCCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("ClaveAcceso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAutorizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("NumeroDocumentoModificado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocialEmisor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RucEmisor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerieComprobante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorSinImpuestos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("NCCompras");
                });

            modelBuilder.Entity("AtsManager.Models.RetencionCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("Anio")
                        .HasColumnType("smallint");

                    b.Property<string>("AutorizacionRetencion")
                        .IsRequired()
                        .HasMaxLength(49)
                        .HasColumnType("nvarchar(49)");

                    b.Property<int>("CargaLoteId")
                        .HasColumnType("int");

                    b.Property<string>("ClaveAccesoSustento")
                        .IsRequired()
                        .HasMaxLength(49)
                        .HasColumnType("nvarchar(49)");

                    b.Property<DateTime?>("FechaAutorizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRetencion")
                        .HasColumnType("datetime2");

                    b.Property<short>("Mes")
                        .HasColumnType("smallint");

                    b.Property<string>("NumRetencion")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NumRetencionCompleto")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("RazonSocialEmisor")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("RucEmisor")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValRetIVA")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ValRetRenta")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CargaLoteId");

                    b.ToTable("RetencionesClientes");
                });

            modelBuilder.Entity("AtsManager.Models.RetencionCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short?>("Anio")
                        .HasColumnType("smallint");

                    b.Property<string>("Autorizacion")
                        .IsRequired()
                        .HasMaxLength(49)
                        .HasColumnType("nvarchar(49)");

                    b.Property<decimal?>("BaseImpAir")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("BaseImpGrav")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("BaseImponible")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("CargaLoteId")
                        .HasColumnType("int");

                    b.Property<string>("CodRetAir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estab")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRetencion")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdProveedor")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<short?>("Mes")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("MontoIva")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("MontoTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("NumComprobante")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NumRetencion")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal?>("PorcentajeAir")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("PtoEmi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocialProveedor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RucEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Secuencial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalRetencion")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ValRetAir")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("ValRetBien10")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("ValRetServ100")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("ValRetServ20")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("ValRetServ50")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("ValorRetBienes")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("ValorRetServicios")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CargaLoteId");

                    b.ToTable("RetencionesCompras");
                });

            modelBuilder.Entity("AtsManager.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short?>("Anio")
                        .HasColumnType("smallint");

                    b.Property<string>("AutorizacionRetencion")
                        .HasMaxLength(49)
                        .HasColumnType("nvarchar(49)");

                    b.Property<decimal?>("BaseImpGrav")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("BaseImponible")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("BaseNoGraIva")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("CargaLoteId")
                        .HasColumnType("int");

                    b.Property<string>("ClaveAcceso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRetencion")
                        .HasColumnType("date");

                    b.Property<string>("FormaPago")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("IdCliente")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<short?>("Mes")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("MontoIce")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("MontoIva")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("MontoTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("NumComprobante")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NumRetencion")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PtoEmi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocialCliente")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RucEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Secuencial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("TipoIdCliente")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("valRetIVA")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("valRetRenta")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CargaLoteId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("AtsManager.Models.Compra", b =>
                {
                    b.HasOne("AtsManager.Models.CargaLote", "CargaLote")
                        .WithMany()
                        .HasForeignKey("CargaLoteId");

                    b.Navigation("CargaLote");
                });

            modelBuilder.Entity("AtsManager.Models.RetencionCliente", b =>
                {
                    b.HasOne("AtsManager.Models.CargaLote", "CargaLote")
                        .WithMany()
                        .HasForeignKey("CargaLoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CargaLote");
                });

            modelBuilder.Entity("AtsManager.Models.RetencionCompra", b =>
                {
                    b.HasOne("AtsManager.Models.CargaLote", "CargaLote")
                        .WithMany()
                        .HasForeignKey("CargaLoteId");

                    b.Navigation("CargaLote");
                });

            modelBuilder.Entity("AtsManager.Models.Venta", b =>
                {
                    b.HasOne("AtsManager.Models.CargaLote", "CargaLote")
                        .WithMany()
                        .HasForeignKey("CargaLoteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CargaLote");
                });
#pragma warning restore 612, 618
        }
    }
}
